[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = ['cd apps/worker && npm ci']

[phases.build]
cmds = ['cd apps/worker && npm run build']

[start]
cmd = 'cd apps/worker && npm start'
